spring:
  application:
    name: user-service

  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - email
              - profile
            # Spring listens to this exact URL by default to catch Google's redirect. Do not need to manually create
            # callback route like we do in node.js
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"

access-token:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  ttl-ms: 60000
  cookie-name: access_token
  cookie-secure: false

refresh-token:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  ttl-ms: 60000
  cookie-name: refresh_token
  cookie-secure: false

frontend:
  redirect-url: "${FRONTEND_URL}/login"
